### ISSUE TITLE
how to save the settings?

### ISSUE THREAD

**Issue by pleasez** [thomasloupe/CleanSweep2#1]
how to save the settings?

**Comment by thomasloupe** [comment]
Could you be a bit more descriptive about which settings you mean?
Are you speaking of the checkboxes or window size, etc?

The window size and other window features save via registry.
Options selected are not saved but they could be. I will create a new feature for this.

**Comment by pleasez** [comment]
Yes, save the cleanup options

**Comment by pleasez** [comment]
Instead of checking your own cleanup items every time

**Comment by pleasez** [comment]
Each time you clean up, you need to re select the items to clean up. How to save your own cleaning options

**Comment by thomasloupe** [comment]
Yes, that feature is not currently available but I am working on it. Thanks for the suggestion.

**Comment by pleasez** [comment]
Thank you very much for your answer

**Comment by pleasez** [comment]
It is Very good tool

**Comment by pleasez** [comment]
I  went to test and clean up win7. Another problem is that when he finds that there is no such path, he will not skip and continue cleaning, but report an error and stop

**Comment by thomasloupe** [comment]
That second issue should be fixed now.
I have released a new version of CleanSweep that now recalls your last sweep.
Please download the latest version here: [2.2.0](https://github.com/thomasloupe/CleanSweep2/releases/tag/v2.2.0)
