### ISSUE TITLE
Error exception + request

### ISSUE THREAD

**Issue by badjawe** [thomasloupe/CleanSweep2#12]
hello,
Une exception non gérée s'est produite dans votre application. Si vous cliquez sur Continuer, l'application va ignorer cette erreur et essayer de continuer. Si vous cliquez sur Quitter, l'application va s'arrêter immédiatement.

Impossible de trouver une partie du chemin d'accès 'C:\Users\louis\AppData\Local\Google\Chrome\User Data'.
An unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and try to continue. If you click Exit, the application will shut down immediately.

Unable to find part of path 'C:\\Users\\louis\\AppData\\Local\\Google\\Chrome\\User Data'.
[cleansweep beta error .txt](https://github.com/user-attachments/files/16829406/cleansweep.beta.error.txt)

Request: could you add options, such as?
Light or dark choice
Choice of text colors
Choice of fonts
Application version
Github connection site
THANKS
[cleansweep beta error .txt](https://github.com/user-attachments/files/16829438/cleansweep.beta.error.txt)

**Comment by thomasloupe** [comment]
Hi!

Can you verify the path in the exception exists:

'C:\Users\louis\AppData\Local\Google\Chrome\User Data'.

I will set up some error handling for this.

Yes, I can add a light and dark theme version. The app version and github website can both be found in the "About" menu.

**Comment by thomasloupe** [comment]
These issues have been addressed in the latest released build. Please confirm it's working as you expect.

**Comment by badjawe** [comment]
Hello,

there is no C:\Users\louis\AppData\Local\Google\Chrome\User Data' ?

I don't use chrome, except maybe with opera portable?
In version 3.beta sorry I didn't see the options, I certainly didn't pay attention at this point.

I tried the new version, no more errors.
THANKS
