### ISSUE TITLE
Running on Win 7

### ISSUE THREAD

**Issue by adeii** [thomasloupe/CleanSweep2#13]
CleanSweep require .Net 4.8.1 which can not be installed to Win 7.
But .Net 4.8 installs on Win 7 and with the same version CleanSweep 3.0 could run. But theme/font colour is not the best choice.
Editing line 9 of CleanSweep.exe.config do the trick. But how to change font or background colour?

![Screenshot_2](https://github.com/user-attachments/assets/9d81401f-0860-43d5-9b91-8641e80f4f6a)

**Comment by thomasloupe** [comment]
Hello,

I have resolved the first issue and will be pushing an update out in just a moment.
In regards to the theme, I have added a new dropdown menu with a Light and Dark theme selection. See below:
![image](https://github.com/user-attachments/assets/648b8a5e-2bb0-4f23-b207-aacd7f6562ae)
and
![image](https://github.com/user-attachments/assets/1d7b9e8d-3040-47b9-ab5e-5cb6c510c95a)

**Comment by thomasloupe** [comment]
This should be resolved now in the latest build. Please confirm.

**Comment by adeii** [comment]
> Please confirm.

I confirm that problem is solved. Both themes are looking good. Thanks for quick solution.

**Comment by thomasloupe** [comment]
Glad to hear it! Thanks very much for your feedback!
