### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by rezorustavi** [thomasloupe/CleanSweep2#2]
Hello, please add russian language.

**Comment by thomasloupe** [comment]
Request accepted. I have begun working on localization for multiple languages.
Currently planned languages: English, German, Spanish, and Russian.

**Comment by rezorustavi** [comment]
Hello. Thank you more for your efforts. How will it be with the Russian translation, please let us know.04.12.2021, 15:51, "Thomas Loupe" ***@***.***>:
Request accepted. I have begun working on localization for multiple languages.
Currently planned languages: English, German, Spanish, and Russian.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- С уважением, Реваз

**Comment by thomasloupe** [comment]
Attempted to write this into current codebase, but it has been difficult and too timely. Striking this feature from the current feature update and will revisit again if time allows.
