### ISSUE TITLE
Errors when using CleanSweep2_GUI

### ISSUE THREAD

**Issue by Massipou** [thomasloupe/CleanSweep2#3]
Hello,

I use cleansweep_GUI 2.3.1 on Windows 11 and Windows 10.

These options don't work :

- **User File History :**
error: Impossible to clean hystoric datas. (error 80040301)

- **Microsoft Office Cache**
error: Unhandled exception has occured in your application ... Access to the path "C:\MSOCache\AllUsers\(XXXXXXXXXX)" is denied

- **Windows Error Report**
error: Impossible to clean hystoric datas. (error 80040301)

Other options work well.
Thanks for your software it is very usefull !

**Comment by thomasloupe** [comment]
Thanks for the report. I'll take a look into it. In the meantime, have you tried running CleanSweep as admin to see if permissions are granted?

**Comment by thomasloupe** [comment]
Since these errors are mostly due to permission issues, or the fact that file history isn't enabled, or that files/folders don't exist, there is additional error handling which shouldn't break CleanSweep now. Fixed in latest version.
https://github.com/thomasloupe/CleanSweep2/releases/tag/v2.3.2.0
