### ISSUE TITLE
GUI exception error

### ISSUE THREAD

**Issue by anonymort** [thomasloupe/CleanSweep2#6]
Runs fine, but on loading the GUI I get the following error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\WINDOWS\SoftwareDistribution\Download\8cfe78f3b9bb72db642451e5794baa3e\amd64_Microsoft-OneCore-ApplicationModel-Sync-Desktop-FOD-Package~~amd64~~10.0.25151.1000\amd64_microsoft-onecore-a..ktop-fod-deployment_31bf3856ad364e35_10.0.25151.1000_none_ecaa90f7957712dc.manifest'.
File name: 'C:\WINDOWS\SoftwareDistribution\Download\8cfe78f3b9bb72db642451e5794baa3e\amd64_Microsoft-OneCore-ApplicationModel-Sync-Desktop-FOD-Package~~amd64~~10.0.25151.1000\amd64_microsoft-onecore-a..ktop-fod-deployment_31bf3856ad364e35_10.0.25151.1000_none_ecaa90f7957712dc.manifest'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at CleanSweep2.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
CleanSweep2
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/userX/Downloads/CleanSweep2.v2.3.3/CleanSweep2.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by thomasloupe** [comment]
Thanks for the report!
I did some research into this, but most of what I'm finding is pointing to the possibility of your machine not running CleanSweep2 as admin, or having debugging keys set in registry for .NET.

The other possibility is that maybe you ran this twice accidentally?
The error was a fatal error on opening, and enabling JIT just allows you to debug the code with Visual Studio in real-time, which probably isn't something you want to do.

Does this happen every time you open the application, and can you get screenshots/additional information about what you were doing, if the user account is an admin, and if the application is running as admin as well?

**Comment by thomasloupe** [comment]
I haven't heard anything back about this issue so I'll proceed with closing it. Please feel free to open a new issue and I'll be happy to assist if I can.
